In [1]:
import numpy as np

In [3]:
NP1 = np.array([1,2,3,4,5,6])#1D array
type(NP1)

numpy.ndarray

In [9]:
NP2 = np.array(([1,2,3],[4,5,6]))#2D array
type(NP2)
NP2
print(NP2.shape, NP2.ndim)

(2, 3) 2


In [12]:
NP1[0]
NP1[3:5]

array([4, 5])

In [13]:
NP2[0]

array([1, 2, 3])

In [15]:
NP2[0][0],NP2[0,0]

(1, 1)

In [17]:
NP2[:,1]

array([2, 5])

In [18]:
import pandas as pd

In [21]:
A = [[1,2,3],[4,5,6],[7,8,9]]
type(A)

list

In [23]:
B = pd.DataFrame(A)
B

0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [24]:
B = pd.DataFrame(A,columns=['col1','col2','col3'],index=['Ex1','Ex2','Ex3'])
B

col1  col2  col3
Ex1     1     2     3
Ex2     4     5     6
Ex3     7     8     9

In [25]:
B.iloc[:,1:3]

col2  col3
Ex1     2     3
Ex2     5     6
Ex3     8     9

In [26]:
B.iloc[0:2,:]

col1  col2  col3
Ex1     1     2     3
Ex2     4     5     6

In [27]:
B.loc['Ex2','col3']

6

In [28]:
B.replace(9,100)

col1  col2  col3
Ex1     1     2     3
Ex2     4     5     6
Ex3     7     8   100

In [29]:
B.replace({5:20,7:30})#to change more than one value in the dataframe, we use dictonaries

col1  col2  col3
Ex1     1     2     3
Ex2     4    20     6
Ex3    30     8     9

In [33]:
C = B.drop('col1',axis=1)
C

col2  col3
Ex1     2     3
Ex2     5     6
Ex3     8     9