In [1]:
import torch
import numpy as np

In [4]:
array1 = np.array([1,2,3])
array1.dtype
type(array1)

numpy.ndarray

In [6]:
tensor1 = torch.tensor([])
type(tensor1)
tensor1.dtype

torch.float32

In [8]:
tensor2 = torch.tensor(array1)
tensor2

tensor([1, 2, 3], dtype=torch.int32)

In [9]:
tensor3 = torch.from_numpy(array1)
tensor3

tensor([1, 2, 3], dtype=torch.int32)

In [11]:
tensor2[1] = 10
tensor2

tensor([ 1, 10,  3], dtype=torch.int32)

In [12]:
array1

array([1, 2, 3])

In [13]:
#torch.from_numpy changes the array without creating a copy where as. torch.tensor creates a copy and not chnage the original array

which activation function to use/ RElu can be used to anytime, sigmoid can be used for classification, 

input layer, hidden layer, output layer
each node in input layer is connected to the hidden layer, the hidden layer nodes are connected to the output layer, 