

**Import** **Libraries**


In [1]:
import numpy as np
import torch

In [4]:
arr1 = np.array([])
#arr1.dtype
type(arr1)

numpy.ndarray

In [7]:
tens1 = torch.tensor([])
#tens1.dtype
type(tens1)

torch.Tensor

In [10]:
arr2 = np.array([1,2,3,4])
#print(arr2)
type(arr2)

numpy.ndarray

In [12]:
tens2 = torch.from_numpy(arr2)
print(tens2)

tensor([1, 2, 3, 4])


In [13]:
tens2[1] = 10
print(tens2)

tensor([ 1, 10,  3,  4])


In [14]:
print(arr2)

[ 1 10  3  4]


In [16]:
arr3 = np.array([10,11,12,13])
tens3 = torch.tensor(arr3)
print(tens3)

tensor([10, 11, 12, 13])


In [17]:
tens3[0] = 200
print(tens3)

tensor([200,  11,  12,  13])


In [18]:
print(arr3)

[10 11 12 13]
